### ISSUE TITLE
titlebar建议增加全局 close 背景色

### ISSUE THREAD

**Issue by Hiram-Wong** [alex8088/electron-uikit#1]
如题

**Comment by alex8088** [comment]
已支持，css 变量为  --tb-control-close-symbol-color

**Comment by Hiram-Wong** [comment]
<img width="297" alt="image" src="https://github.com/user-attachments/assets/676c3f3b-ebb8-41be-a120-88939fe65019" />

`"@electron-uikit/titlebar": "^1.2.0"`版本中 f12 未生效--tb-control-close-symbol-color, 实际任然为写死状态

**Comment by Hiram-Wong** [comment]
> 已支持，css 变量为 --tb-control-close-symbol-color

<img width="297" alt="image" src="https://github.com/user-attachments/assets/676c3f3b-ebb8-41be-a120-88939fe65019" />

`"@electron-uikit/titlebar": "^1.2.0"`版本中 f12 查看close-hover为写死状态, 是不是理解有误

同时文档似乎也没有增加对--tb-control-close-symbol-color的说明
